#!/bin/bash

# One-Click Deployment Script for Telegram Archiver Microservices
# Author: Auto-generated deployment automation
# Usage: ./deploy_all.sh

set -e  # Exit on any error

echo "🚀 Telegram Archiver Microservices Deployment"
echo "=============================================="

# Step 0: Pre-flight Checks
echo ">>> Pre-flight checks..."

# Check if wrangler is installed
if ! command -v wrangler &> /dev/null; then
    echo "❌ Error: wrangler CLI is not installed."
    echo "Please install it with: npm install -g wrangler"
    exit 1
fi

echo "✅ Wrangler CLI found"

# Interactive input for Cloudflare subdomain
echo ""
read -p "Enter your Cloudflare Workers Subdomain (e.g., your-name): " SUB_DOMAIN

if [ -z "$SUB_DOMAIN" ]; then
    echo "❌ Error: Subdomain cannot be empty"
    exit 1
fi

echo "✅ Using subdomain: $SUB_DOMAIN"

# Step 1: Database Migration (D1)
echo ""
echo ">>> Applying D1 Migrations..."
cd api

# Apply migrations with auto-confirmation
echo "Running: npx wrangler d1 migrations apply DB --remote"
npx wrangler d1 migrations apply DB --remote --yes

echo "✅ D1 migrations applied successfully"

# Step 2: Deploy Workers (Microservices)
echo ""
echo ">>> Deploying Microservices..."

# Deploy Scanner (Worker A)
echo "Deploying Scanner Worker..."
npx wrangler deploy
echo "✅ Scanner deployed successfully"

# Deploy Processor (Worker B)
echo "Deploying Processor Worker..."
cd ../api/processor
npx wrangler deploy
echo "✅ Processor deployed successfully"

# Deploy Viewer (Worker C)
echo "Deploying Viewer Worker..."
cd ../api/viewer
npx wrangler deploy
echo "✅ Viewer deployed successfully"

# Return to root directory
cd ../../

# Step 3: Construct URLs
echo ""
echo ">>> Constructing Service URLs..."
SCANNER_URL="https://telegram-archiver-api.${SUB_DOMAIN}.workers.dev"
PROCESSOR_URL="https://telegram-processor.${SUB_DOMAIN}.workers.dev"
VIEWER_URL="https://telegram-viewer.${SUB_DOMAIN}.workers.dev"

echo "📍 Service URLs:"
echo "  Scanner:   $SCANNER_URL"
echo "  Processor: $PROCESSOR_URL"
echo "  Viewer:    $VIEWER_URL"

# Step 4: Auto-Configure Frontend
echo ""
echo ">>> Updating UI Configuration..."

# Create new api.js with real URLs
cat > ui/src/utils/api.js << EOF
// Auto-generated by deploy_all.sh
// Microservice URLs for deployment
const SCANNER_URL = "${SCANNER_URL}";
const PROCESSOR_URL = "${PROCESSOR_URL}";
const VIEWER_URL = "${VIEWER_URL}";

// Legacy fallback for backward compatibility
const API_BASE = SCANNER_URL;

// Create a fetch function that adds the access key to all requests
export const createAuthenticatedFetch = () => {
  return async (url, options = {}) => {
    // Get access key from localStorage (since we can't use hooks in utils)
    const accessKey = localStorage.getItem('access-key-storage');
    const parsedAccessKey = accessKey ? JSON.parse(accessKey).state?.accessKey : null;
    
    const headers = {
      'Content-Type': 'application/json',
      ...options.headers,
    };
    
    if (parsedAccessKey) {
      headers['X-Access-Key'] = parsedAccessKey;
    }
    
    return fetch(url, {
      ...options,
      headers,
    });
  };
};

export const authenticatedFetch = createAuthenticatedFetch();

// Export microservice URLs for stores to use
export { API_BASE, SCANNER_URL, PROCESSOR_URL, VIEWER_URL };
EOF

echo "✅ UI configuration updated with real URLs"

# Step 5: Deploy Frontend
echo ""
echo ">>> Building and Deploying UI..."
cd ui

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing UI dependencies..."
    npm install
fi

# Build the frontend
echo "Building frontend..."
npm run build

# Deploy to Cloudflare Pages
echo "Deploying to Cloudflare Pages..."
npx wrangler pages deploy dist --project-name telegram-archiver-ui

echo "✅ Frontend deployed successfully"

# Return to root directory
cd ..

# Final Summary
echo ""
echo "🎉 Deployment Complete!"
echo "======================="
echo "📍 Your Services:"
echo "  Scanner API:   $SCANNER_URL"
echo "  Processor API: $PROCESSOR_URL"
echo "  Viewer API:    $VIEWER_URL"
echo ""
echo "🌐 Frontend will be available at your Cloudflare Pages domain"
echo ""
echo "📋 Next Steps:"
echo "  1. Visit your frontend URL"
echo "  2. Configure Telegram credentials"
echo "  3. Start archiving!"
echo ""
echo "✨ Happy archiving!"
