// Auto-generated by deploy_all.sh for iflove29 deployment
// Microservice URLs for deployment
const SCANNER_URL = "https://telegram-archiver-api.iflove29.workers.dev";
const PROCESSOR_URL = "https://telegram-processor.iflove29.workers.dev";
const VIEWER_URL = "https://telegram-viewer.iflove29.workers.dev";

// Legacy fallback for backward compatibility
const API_BASE = SCANNER_URL;

// Create a fetch function that adds the access key to all requests
export const createAuthenticatedFetch = () => {
  return async (url, options = {}) => {
    // Get access key from localStorage (since we can't use hooks in utils)
    const accessKey = localStorage.getItem('access-key-storage');
    const parsedAccessKey = accessKey ? JSON.parse(accessKey).state?.accessKey : null;
    
    const headers = {
      'Content-Type': 'application/json',
      ...options.headers,
    };
    
    if (parsedAccessKey) {
      headers['X-Access-Key'] = parsedAccessKey;
    }
    
    return fetch(url, {
      ...options,
      headers,
    });
  };
};

export const authenticatedFetch = createAuthenticatedFetch();

// Export microservice URLs for stores to use
export { API_BASE, SCANNER_URL, PROCESSOR_URL, VIEWER_URL };
